---
title: "VSLite Sensitivity Analysis"
format: html
server: shiny
toc: true
---

```{r}
#| label: Preparing the workspace
#| context: setup
#| echo: false
#| message: false
#| warning: false
#| results: false
source("External/Vs.R", local = FALSE)
library(VSLiteR)
library(dplR) # for reading in dendro data
library(ggplot2) # for plotting later
library(tidyverse)
library(DEoptim)
library(shiny)
```

```{r}
#| echo: false
#| message: false
#| warning: false
#| context: data
#| results: false

beech <- read.rwl("Data/buche_chrono.rwl")
climate <- read.csv2("Data/climate_bausenberg.csv")[, c(1, 2, 3, 6)]
spruce <- read.rwl("Data/spruce_alpine.rwl")
climate_alpine <- read.csv2("Data/climate_alpine.csv")
cordex_alpine <- read.csv2("Data/lfu_cordex_ensemble_monthly_alpine.csv")
cordex_beech <- read.csv2("Data/lfu_cordex_ensemble_monthly_beech.csv")
```

## Beech

### Calibration

```{r}
#| cache: true
#| include: false
input_historic <- make_vsinput_historic(beech, climate)

beech_params <- vs_params(input_historic$trw,
                          input_historic$tmean,
                          input_historic$prec,
                          input_historic$syear,
                          input_historic$eyear,
                          .phi = 50) # approx. latitude in degrees
```

### Sensitivity analysis

```{r}
sliderInput("T1_beech", "T1 Beech", min = 0,
            max = 8.5, value = beech_params[1])
sliderInput("T2_beech", "T2 Beech", min = 9,
            max = 20, value = beech_params[2])
sliderInput("M1_beech", "M1 Beech", min = 0.01,
            max = 0.03, value = beech_params[3])
sliderInput("M2_beech", "M2 Beech", min = 0.1,
            max = 0.5, value = beech_params[4])
plotOutput("beech_sensitivity_rcp")
```

```{r}
#| context: server
output$beech_sensitivity_rcp <- renderPlot({
  
  beech_params2 <- c(
    T1 = input$T1_beech,
    T2 = input$T2_beech,
    M1 = input$M1_beech,
    M2 = input$M2_beech
  )
  
  input_transient <- make_vsinput_transient(climate)
  
  beech_forward <- vs_run_forward(beech_params2,
                                  input_transient$tmean,
                                  input_transient$prec,
                                  input_transient$syear,
                                  input_transient$eyear,
                                  .phi = 50)
  
  make_forward_model <- function(x) {
    input <- make_vsinput_transient(x)
    vs_run_forward(beech_params2,
                   input$temp,
                   input$prec,
                   input$syear,
                   input$eyear,
                   .phi = 50)
  }
  
  forward_beech <- cordex_beech %>% 
    filter(year > 2020) %>% 
    group_by(rcp, gcm, rcm) %>% 
    filter(length(year) == 80 * 12) %>% 
    nest() %>% 
    mutate(vs_forward = purrr::map(data, make_forward_model)) %>% 
    unnest(vs_forward)
  
  smooth_trw <- function(x) {
    trw <- predict(loess(trw ~ year, data = x))
    data.frame(
      year = x$year,
      trw = trw
    )
  }
  
  forward_beech %>% 
    group_by(rcp, gcm, rcm) %>% 
    nest() %>% 
    mutate(trw = map(data, smooth_trw)) %>%
    unnest(trw) %>% 
    group_by(rcp, year) %>% 
    summarise(
      trw_sd = sd(trw),
      trw = mean(trw)
    ) %>% 
    ggplot(aes(year, trw)) +
    geom_ribbon(aes(ymin = trw - trw_sd, ymax = trw + trw_sd)) +
    geom_line(colour = "red") +
    facet_wrap(~ rcp)
})
```


## Spruce

### Calibration

```{r}
#| include: false
#| cache: true
spruce_input_historic <- make_vsinput_historic(spruce, climate_alpine)

spruce_params <- vs_params(spruce_input_historic$trw,
                           spruce_input_historic$temp,
                           spruce_input_historic$prec,
                           spruce_input_historic$syear,
                           spruce_input_historic$eyear,
                           .phi = 50) # approx. latitude in degrees
```

### Sensitivity analysis

```{r}
sliderInput("T1_spruce", "T1 Spruce", min = 0,
            max = 8.5, value = spruce_params[1])
sliderInput("T2_spruce", "T2 Spruce", min = 9,
            max = 20, value = spruce_params[2])
sliderInput("M1_spruce", "M1 Spruce", min = 0.01,
            max = 0.03, value = spruce_params[3])
sliderInput("M2_spruce", "M2 Spruce", min = 0.1,
            max = 0.5, value = spruce_params[4])
shiny::selectInput("rcp_spruce", "Szenario",
                   choices = c("RCP_85", "RCP_45", "RCP_26"))
plotOutput("spruce_sensitivity")
textOutput("spruce_correlation") 
```

```{r}
#| context: server
output$spruce_sensitivity <- renderPlot({
  
  spruce_params2 <- c(
    T1 = input$T1_spruce,
    T2 = input$T2_spruce,
    M1 = input$M1_spruce,
    M2 = input$M2_spruce
  )
  
  input_transient <- make_vsinput_transient(climate_alpine)
  
  spruce_forward <- vs_run_forward(spruce_params2,
                                  input_transient$temp,
                                  input_transient$prec,
                                  input_transient$syear,
                                  input_transient$eyear,
                                  .phi = 50)
  rcp_input <- cordex_alpine %>% 
    filter(year > 2020, rcp == input$rcp_spruce) %>% 
    group_by(year, month) %>% 
    summarise(
      tmean = mean(temp),
      prec = mean(prec)
    ) %>% 
    ungroup() %>% 
    make_vsinput_transient()
  
   spruce_forward_rcp <- vs_run_forward(spruce_params2,
                                      rcp_input$tmean,
                                      rcp_input$prec,
                                      rcp_input$syear,
                                      rcp_input$eyear,
                                      .phi = 50)
  
  names(spruce_forward_rcp) <- c("year", "projection")
  
  
  spruce_observed <- data.frame(
    year = as.numeric(rownames(spruce)),
    observed = scale(spruce$std)
  )
  
  spruce_combined <- merge(spruce_observed, spruce_forward)
  spruce_combined$modelled <- scale(spruce_combined$trw)
  spruce_combined$trw <- NULL
  spruce_combined <- merge(spruce_combined, spruce_forward_rcp, all = TRUE)
  # print(head(spruce_combined)) 
  spruce_combined <- tidyr::pivot_longer(
    spruce_combined, -1, 
    names_to = "variant",
    values_to = "rwi")
  
  correlation <- cor(spruce_combined$rwi [spruce_combined$variant == "modelled"], 
     spruce_combined$rwi [spruce_combined$variant == "observed"])
  
  ggplot(spruce_combined, aes(year, rwi)) +
    geom_line(aes(colour = variant)) +
    labs(title = paste0("correlation = ", round(correlation, 2))) +
    geom_smooth(aes(colour = variant), se = FALSE)
})
```
