---
title: "Vs-lite"
author: "Peter, James, Zanna"
format: html
editor: visual
execute: 
  echo: false
---

## Prepare Data

```{r}
#| echo: true
#| results: false
#| message: false
#| warning: false
source("External/Vs.R")
library(VSLiteR)
library(dplR) # for reading in dendro data
library(ggplot2) # for plotting later
library(tidyverse)
library(DEoptim)
```

## Prepare Input Data

```{r}
#| echo: true
#| results: false
#| message: false
#| warning: false

beech <- read.rwl("Data/buche_chrono.rwl")
climate <- read.csv2("Data/climate_bausenberg.csv")[, c(1, 2, 3, 6)]
spruce <- read.rwl("Data/spruce_alpine.rwl")
climate_spruce <- read.csv2("Data/climate_alpine.csv")
```

## Call to verify tree data load

```{r}
head(beech, 3)
```

## Call to verify climate data load

```{r}
head(climate, 3)
```

## Calibration run and Run model Forward

```{r}
#| echo: true
#| message: false
#| warning: false
#| cache: true
#| results: false

input_historic <- make_vsinput_historic(beech, climate)

beech_params <- vs_params(input_historic$trw,
                          input_historic$tmean,
                          input_historic$prec,
                          input_historic$syear,
                          input_historic$eyear,
                          .phi = 50) # approx. latitude in degrees

input_transient <- make_vsinput_transient(climate)

beech_forward <- vs_run_forward(beech_params,
                                input_transient$tmean,
                                input_transient$prec,
                                input_transient$syear,
                                input_transient$eyear,
                                .phi = 50)
```

## Compare the model and observation

```{r}
beech_observed <- data.frame(
  year = as.numeric(rownames(beech)),
  observed = scale(beech$bee)
)

beech_combined <- merge(beech_observed, beech_forward)
beech_combined$modelled <- scale(beech_combined$trw)
beech_combined$trw <- NULL
beech_combined <- tidyr::pivot_longer(beech_combined, -1, names_to = "variant",
                                      values_to = "rwi")

ggplot(beech_combined, aes(year, rwi)) +
  geom_line(aes(colour = variant))

cor (beech_combined$rwi [beech_combined$variant == "modelled"], 
     beech_combined$rwi [beech_combined$variant == "observed"])
```

## Correlation of sensitive parameter

```{r}
M2_params <- c(T1 = 0, T2 = 9, M1 = 0.01, M2 = 0.1)

M2_forward <- vs_run_forward(M2_params,
                      input_transient$tmean,
                      input_transient$prec,
                      input_transient$syear,
                      input_transient$eyear,
                      .phi = 50,)

M2_combined <- merge(beech_observed, M2_forward)
M2_combined$modelled <- scale(M2_combined$trw)
M2_combined$trw <- NULL
M2_combined <- tidyr::pivot_longer(M2_combined, -1, names_to = "variant",
                           values_to = "rwi")

ggplot(M2_combined, aes(year, rwi)) +
  geom_line(aes(colour = variant))

cor (M2_combined$rwi [M2_combined$variant == "modelled"], 
     M2_combined$rwi [M2_combined$variant == "observed"])

```

## Calibration Run 

```{r}
#| echo: true
#| message: false
#| warning: false
#| cache: true
#| results: false

input_historic_s <- make_vsinput_historic(spruce, climate_alpine)

spruce_params <- vs_params(input_historic_s$trw,
                          input_historic_s$temp,
                          input_historic_s$prec,
                          input_historic_s$syear,
                          input_historic_s$eyear,
                          .phi = 50) # approx. latitude in degrees
```


## Run model Forward

```{r}
input_transient_s <- make_vsinput_transient(climate_alpine)

spruce_forward <- vs_run_forward(spruce_params,
                                input_transient_s$temp,
                                input_transient_s$prec,
                                input_transient_s$syear,
                                input_transient_s$eyear,
                                .phi = 50)
```


## Compare model and observation

```{r}
spruce_observed <- data.frame(
  year = as.numeric(rownames(spruce)),
  observed = scale(spruce$std)
)

spruce_combined <- merge(spruce_observed, spruce_forward)
spruce_combined$modelled <- scale(spruce_combined$trw)
spruce_combined$trw <- NULL
spruce_combined <- tidyr::pivot_longer(spruce_combined, -1, names_to = "variant",
                                      values_to = "rwi")

ggplot(spruce_combined, aes(year, rwi)) +
  geom_line(aes(colour = variant))

cor (spruce_combined$rwi [spruce_combined$variant == "modelled"], 
     spruce_combined$rwi [spruce_combined$variant == "observed"])

```


## Correlation of sensitive parameters 

```{r}
T2_params <- c(T1 = 6.5, T2 = 20, M1 = 0.01, M2 = 0.5)

T2_forward <- vs_run_forward(T2_params,
                     input_transient_s$temp,
                     input_transient_s$prec,
                     input_transient_s$syear,
                     input_transient_s$eyear,
                     .phi = 50)

T2_combined <- merge(spruce_observed, T2_forward)
T2_combined$modelled <- scale(T2_combined$trw)
T2_combined$trw <- NULL
T2_combined <- tidyr::pivot_longer(T2_combined, -1, names_to = "variant",
                          values_to = "rwi")

ggplot(T2_combined, aes(year, rwi)) +
  geom_line(aes(colour = variant))

cor (T2_combined$rwi [T2_combined$variant == "modelled"], 
     T2_combined$rwi [T2_combined$variant == "observed"])

```

